### ISSUE TITLE
server not start up

### ISSUE THREAD

**Issue by nickbus60** [RigsOfRods/ror-server#44]
i go to start the server this what i get 
![2017-05-22](https://cloud.githubusercontent.com/assets/18500535/26325617/a0c48f4c-3f05-11e7-81a7-4ce5097d9206.png)

**Comment by Strykr1** [comment]
Using the GUI is not supported

**Comment by Michael10055** [comment]
The `admins.txt` error shouldn't prevent the server from starting up. Since authorizations are not supported on the latest version, just remove the `authfile` line from your server's main `.cfg` file.

It is recommended to use the command prompt to start the server:
http://docs.rigsofrods.org/gameplay/multiplayer-server-setup/#running-the-server

**Comment by nickbus60** [comment]
will it  up for 2 min then i will stop reponing 
![2017-05-23](https://cloud.githubusercontent.com/assets/18500535/26509605/7846fa4e-4227-11e7-8234-9213b01e3146.png)

**Comment by Michael10055** [comment]
Looks like you're using a older rorserver version that doesn't support the new master server. 
Add (or change) the `mode` option to `lan` in your server's `.cfg`:
```
## server mode. either inet or lan
mode = lan
```
