### ISSUE TITLE
CMake: Auto-generate ctemplate headers for OS

### ISSUE THREAD

**Issue by Hiradur** [RigsOfRods/ror-server#7]
WITH_WEBSERVER does not build properly on Linux.

```
[ 76%] Building CXX object source/server/CMakeFiles/rorserver.dir/webserver.cpp.o
/home/hiradur/Desktop/ror-server/source/server/webserver.cpp:46:32: fatal error: ctemplate/template.h: No such file or directory
 #include <ctemplate/template.h>
                                ^
compilation terminated.
make[2]: *** [source/server/CMakeFiles/rorserver.dir/webserver.cpp.o] Error 1
```

ctemplate headers have to be generated for the OS in use which causes the headache here.

**Comment by Hotrod55** [comment]
Has anyone looked into this? Would be great to get it working again.

**Comment by Hiradur** [comment]
> Would be great to get it working again.

Did the webserver ever work on Linux?
Just to make it clear, the server itself works but the webinterface to configure it through a browser will be missing.

**Comment by Hotrod55** [comment]
I don't know if the webserver ever worked on Linux, but it's needed for this http://www.rigsofrods.com/threads/105847-Server-Administration-Panel 
The panel itself works, but the ability to view logs requires webserver support so it doesn't work. :/

**Comment by Hiradur** [comment]
May be fixed by https://github.com/RigsOfRods/ror-server/commit/2b46a79861f90812aa0b4c3f1cf4ca1d43cb949d but I didn't test.

**Comment by Hotrod55** [comment]
Compiles & runs fine, the webserver pages though only work in some browsers and the Stats/Log/Chat tabs are unfinished.
Edge:
![2016-03-30_16-47-25](https://cloud.githubusercontent.com/assets/11002490/14157183/eb3a8c50-f697-11e5-8697-c23a2b39e762.png)
![2016-03-30_16-54-03](https://cloud.githubusercontent.com/assets/11002490/14157227/168a38f6-f698-11e5-8c1f-02bfa3c942fe.png)
Firefox Developer Edition 47.0a2 (2016-03-28) doesn't render the page at all:
![2016-03-30_16-59-42](https://cloud.githubusercontent.com/assets/11002490/14157405/db1629b4-f698-11e5-9116-5d29d76e506a.png)
Since the webserver pages were most likely never finished, this is not a issue with the rorserver client itself, I'd say it is fixed. :smile:

**Comment by dalanlan** [comment]
Hi @Hiradur I was involved into a project making use of ctemplate. However it's not properly linked within the project itself. I was wondering how you get the copy of the ctemplate in dir `/dependency` and I just want to follow your path. Thanks in advance.

os: ubuntu 14.04

**Comment by only-a-ptr** [comment]
@dalanlan Hello. 
Unfortunately @Hiradur has retired from this project and won't come around to answer your question.
I have only essential knowledge of CMake myself, so I can't hel you either.
Cheers.

**Comment by dalanlan** [comment]
@only-a-ptr I guess [this](https://github.com/olafvdspek/ctemplate) would help, for anyone else who might be interested in. Thanks anyway.
